import { useEffect, useRef } from "react";
import { SESSION_KEYS } from "@/src/lib/mcp-auth";
import { auth } from "@modelcontextprotocol/sdk/client/auth.js";
import { InspectorOAuthClientProvider } from "@/src/lib/mcp-auth";
import { redirect } from "next/navigation";

type CallbackParams =
	| {
		successful: true;
		// The authorization code is generated by the authorization server.
		code: string;
	}
	| {
		successful: false;
		// The OAuth 2.1 Error Code.
		// Usually one of:
		//    ```
		//    invalid_request, unauthorized_client, access_denied, unsupported_response_type,
		//    invalid_scope, server_error, temporarily_unavailable
		//    ```
		error: string;
		// Human-readable ASCII text providing additional information, used to assist the
		// developer in understanding the error that occurred.
		error_description: string | null;
		// A URI identifying a human-readable web page with information about the error,
		// used to provide the client developer with additional information about the error.
		error_uri: string | null;
	};

export const parseOAuthCallbackParams = (location: string): CallbackParams => {
	const params = new URLSearchParams(location);

	const code = params.get("code");
	if (code) {
		return { successful: true, code };
	}

	const error = params.get("error");
	const error_description = params.get("error_description");
	const error_uri = params.get("error_uri");

	if (error) {
		return { successful: false, error, error_description, error_uri };
	}

	return {
		successful: false,
		error: "invalid_request",
		error_description: "Missing code or error in response",
		error_uri: null,
	};
};

/**
 * Generate a random state for the OAuth 2.0 flow.
 *
 * @returns A random state for the OAuth 2.0 flow.
 */
export const generateOAuthState = () => {
	// Generate a random state
	const array = new Uint8Array(32);
	crypto.getRandomValues(array);
	return Array.from(array, (byte) => byte.toString(16).padStart(2, "0")).join(
		"",
	);
};

/**
 * Generates a human-readable error description from OAuth callback error parameters
 * @param params OAuth error callback parameters containing error details
 * @returns Formatted multiline error message with error code, description, and optional URI
 */
export const generateOAuthErrorDescription = (
	params: Extract<CallbackParams, { successful: false }>,
): string => {
	const error = params.error;
	const errorDescription = params.error_description;
	const errorUri = params.error_uri;

	return [
		`Error: ${error}.`,
		errorDescription ? `Details: ${errorDescription}.` : "",
		errorUri ? `More info: ${errorUri}.` : "",
	]
		.filter(Boolean)
		.join("\n");
};
interface OAuthCallbackProps {
	onConnect: (serverUrl: string) => void;
}

const OAuthCallback = ({ onConnect }: OAuthCallbackProps) => {
	const hasProcessedRef = useRef(false);

	useEffect(() => {
		const handleCallback = async () => {
			// Skip if we've already processed this callback
			if (hasProcessedRef.current) {
				return;
			}
			hasProcessedRef.current = true;

			const notifyError = (description: string) =>
				console.error({
					title: "OAuth Authorization Error",
					description,
					variant: "destructive",
				});

			const params = parseOAuthCallbackParams(window.location.search);
			if (!params.successful) {
				return notifyError(generateOAuthErrorDescription(params));
			}

			const serverUrl = sessionStorage.getItem(SESSION_KEYS.SERVER_URL);
			if (!serverUrl) {
				return notifyError("Missing Server URL");
			}

			let result;
			try {
				// Create an auth provider with the current server URL
				const serverAuthProvider = new InspectorOAuthClientProvider(serverUrl);

				result = await auth(serverAuthProvider, {
					serverUrl,
					authorizationCode: params.code,
				});
			} catch (error) {
				console.error("OAuth callback error:", error);
				return notifyError(`Unexpected error occurred: ${error}`);
			}

			if (result !== "AUTHORIZED") {
				return notifyError(
					`Expected to be authorized after providing auth code, got: ${result}`,
				);
			}

			// Finally, trigger auto-connect
			console.log({
				title: "Success",
				description: "Successfully authenticated with OAuth",
				variant: "default",
			});
			onConnect(serverUrl);
		};

		handleCallback().finally(() => {
			window.history.replaceState({}, document.title, "/");
			redirect("/");
		});
	}, [onConnect]);

	return (
		<div className="flex items-center justify-center h-screen">
			<p className="text-lg text-gray-500">Processing OAuth callback...</p>
		</div>
	);
};

export default OAuthCallback;
